### ISSUE TITLE
Encourage avoidance of duplicated code?

### ISSUE THREAD

**Issue by claremacrae** [marcusolsson/obsidian-plugin-docs#8]
I’m not sure how much you want to focus on general good development practices…

But when I see the “Print file path” example in [Context Menus](https://marcus.se.net/obsidian-plugin-docs/guides/context-menus) I have the urge to refactor to remove the duplicated code… For lots of reasons, including foreseeing the inevitable future bug-fix or new feature where the two accidentally become inconsistent.

The current code is good from an explanatory perspective, though… So I wonder whether it’s worth a second example that shows doing the same thing, but having the common code moved to something like a local helper function - named so that it either creates the one menu item - or to add all the menu items, as the plugin grows.

**Comment by SkepticMystic** [comment]
Related to this topic, the `obsidian-community-lib` was made to avoid duplicating code across plugins, and to have a community-maintained set of functions.
Maybe you can mention the lib somewhere and encourage authors to review and add to the code so that we have a standardised way of doing common things
